config:
  hour: 0
  minimum_players_sleep_needed: 1 #I suck at naming pls don't kill me
  death_train_seconds: 3600
  discord_webhooks: []
  starting_lives: 3
  rabies_seconds: 1200 # 20 minutes
  grace_period: 300 # 5 minutes, seconds on which players won't take damage after dying
messages:
  prefix: "&8[&4&lPermadeath&r&8]&r "
  player_banned: "&c&lPERMADEATH!&r\nYou have died and are no longer allowed to join back" #f*ck no im not making it a list
  player_joined: "&c%s has joined Hell. (%d lifes)" #yeah im also not using %player% hell nawh
  texture_pack: "&e&lPlease accept the resourcepack for improved experience"
  texture_pack_denied: "Please accept the resource pack."
  current_day: "&aCurrently in day: &c%d"
  permadeath_title: "&cPERMADEATH!"
  permadeath_subtitle: "%s has died!"
  death_train_enabled: "&cDEATH TRAIN ACTIVE FOR %d HOUR(S)"
  permadeath_kick_reason: "&c&lPERMADEATH&r\nYou have died. GGWP"
  remaining_lifes: "&c&lYOU HAVE %d LIFE(S) REMAINING. BE CAREFUL"
  death_train: "&7Death Train: %02d:%02d:%02d"
  sleeping_disabled: "&cSleeping is disabled"
  sleeping_disabled_deathtrain: "&cYou can't sleep. It's Death Train"
  upgrade_netherite_failed: "&cYou can't do that!"
  totem_failed: "&cHow unfortunate. %s's totem did not work. Oh well, too bad"
  totem_worked: "&7%s activated a Totem of Undying. Luckily, they have survived. (%d > %d)"
  jesus_totem: "&dThis totem has a 100%% chance of working"
  jesus_totem_used: "&7%s activated a Jesus Totem of Undying (100%% chance of working)"
  bed_anchor_disabled_end: "&cThis is disabled in The End"
  discord_webhook_died: "%s HAS DIED!"
  discord_webhook_totem: "%s popped a Totem!"
  discord_webhook_jesus_totem: "%s popped a Jesus Totem!"
  motd_before_day_30: "You won't last longer than 30 seconds... wait"
  motd_day_30: "                 &c&l&kii &4&lWELCOME TO HELL &c&l&kii"
  dragon_heal: "&cDemon is healing itself!"
  jump_disabled: "&cYou can't jump!"
  rabies_infected: "&cYou have been infected with rabies, drink a milk bucked within the next %d minutes or you'll die. Disconnecting before that time will also kill you"
  rabies_timer: "&7Find a cure before: %02d:%02d:%02d"
  rabies_cured: "&aYou have been cured!"
  extra_heart_gained: "&aYou've gained 1 extra heart"
  extra_heart_limit_reached: "&cYou've exceeded the amount of times you can consume this"
  grace_period_removed: "&cYour grace period has been removed. Be careful"