main: pd.guimx.Permadeath
version: 2.8.2
name: Permadeath
author: guimx
api-version: 1.21.4
description: meow
depend: [ProtocolLib]

commands:
  permadeath:
    aliases:
      - pd
    description: Permadeath command
    permission: pd.main