main: pd.guimx.Permadeath
version: 2.0.0
name: Permadeath
author: guimx
api-version: 1.21.1
description: meow

commands:
  permadeath:
    aliases:
      - pd
    description: Permadeath command
    permission: pd.main