main: pd.guimx.Permadeath
version: 2.7.3
name: Permadeath
author: guimx
api-version: 1.21.3
description: meow
depend: [ProtocolLib]

commands:
  permadeath:
    aliases:
      - pd
    description: Permadeath command
    permission: pd.main